export const LOCATIONS = [
    {
        id: 1,
        name: "Parque do Ibirapuera",
        type: "Parque Urbano",
        lat: -23.5874,
        lon: -46.6576,
    },
    {
        id: 2,
        name: "Avenida Paulista",
        type: "Área Urbana",
        lat: -23.5617,
        lon: -46.6560,
    },
    {
        id: 3,
        name: "Praça da Sé",
        type: "Centro Histórico",
        lat: -23.5505,
        lon: -46.6333,
    },
    {
        id: 4,
        name: "Jardim Botânico",
        type: "Reserva Botânica",
        lat: -23.6394,
        lon: -46.6200,
    },
    {
        id: 5,
        name: "Represa de Guarapiranga",
        type: "Área de Manancial",
        lat: -23.6934,
        lon: -46.7334,
    },
    {
        id: 6,
        name: "Horto Florestal",
        type: "Floresta Urbana",
        lat: -23.4561,
        lon: -46.6358,
    },
    {
        id: 7,
        name: "Parque Villa-Lobos",
        type: "Parque Urbano",
        lat: -23.5460,
        lon: -46.7245,
    },
    {
        id: 8,
        name: "Pico do Jaraguá",
        type: "Área de Preservação",
        lat: -23.4560,
        lon: -46.7629,
    },
    {
        id: 9,
        name: "Serra da Cantareira",
        type: "Parque Estadual",
        lat: -23.4116,
        lon: -46.6067,
    },
    {
        id: 10,
        name: "Autódromo de Interlagos",
        type: "Área Verde Periférica",
        lat: -23.7011,
        lon: -46.6974,
    },
];
